const sentences = [
  "It seemed to him that misfortune followed wherever he went",
  "Then he threw his head back and laughed",
  "He hailed it and in a low voice gave the driver an address",
  "I see things differently, I think of them differently",
  "I am forced to bring you into the matter",
  "A bitter blast swept across the square",
  "I thought that I was going to be wonderful",
  "You laugh, but I tell you she has genius",
  "I know now that I was quite right in what I fancied about him",
  "Those who go beneath the surface do so at their peril",
  "To be in love is to surpass one's self",
  "She never gets confused over her dates, and I always do",
  "And yet the thing would still live on",
  "She tells me she is going down to Selby",
  "It is my masterpiece as it stands",
  "But I am much obliged for the compliment, all the same",
  "It might be a most brilliant marriage for Sibyl",
  "Most of the servants were at Selby Royal",
  "The ugly and the stupid have the best of it in this world",
  "Success was given to the strong, failure thrust upon the weak",
  "He came close to him and put his hand upon his shoulder",
  "Her love was trembling in laughter on her lips",
  "It will be a great pity, for it will alter you",
  "It is too ugly, too horrible, too distressing",
  "I came here at once and was miserable at not finding you",
  "The knocking still continued and grew louder",
  "Her companion watched her enviously",
  "Now, wherever you go, you charm the world",
  "He lit a cigarette and then threw it away",
  "The lad listened sulkily to her and made no answer",
  "Gray to wait, Parker: I shall be in in a few moments",
  "Yes: it was certainly a tedious party",
  "There were tears in his eyes as he went downstairs",
  "He would never bring misery upon any one",
  "It was of himself, and of his own future, that he had to think",
  "The man looked at her in terror and began to whimper",
  "And they passed into the dining-room",
  "You gave her good advice and broke her heart",
  "They are horrible, and they don't mean anything",
  "They have had my own divorce-case and Alan Campbell's suicide",
  "Make my excuses to Lady Narborough",
  "Harry, to whom I talked about it, laughed at me",
  "A decent-looking man, sir, but rough-like",
  "Dorian looked at him for a moment",
  "In one of the top-windows stood a lamp",
  "There had been a madness of murder in the air",
  "Of course, I am very fond of Harry",
  "The artist is the creator of beautiful things",
  "That is a great advantage, don't you think so, Mr",
  "Erskine, an absolutely reasonable people",
  "I am analysing women at present, so I ought to know",
  "He felt as if the load had been lifted from him already",
  "But here was a visible symbol of the degradation of sin",
  "The little duchess is quite devoted to you",
  "They are the elect to whom beautiful things mean only beauty",
  "But I wish you had left word where you had really gone to",
  "I know you are surprised at my talking to you like this",
  "The sunlight slipped over the polished leaves",
  "A curious sensation of terror came over me",
  "He was heart-sick at leaving home",
  "People say sometimes that beauty is only superficial",
  "It was merely the name men gave to their mistakes",
  "Lord Henry shrugged his shoulders",
  "It was the most premature definition ever given",
  "It will be a great pity, for it will alter you",
  "It had been given to him by Adrian Singleton",
  "At last he heard a step outside, and the door opened",
  "They have a right to demand it back",
  "There is no mystery in any of them",
  "When Lord Henry had sat down again, Mr",
  "Besides, individualism has really the higher aim",
  "You find me consoled, and you are furious",
  "This one is little more than a boy",
  "Come to the club with Basil and myself",
  "The man who had been shot in the thicket was James Vane",
  "One could hear her singing as she ran upstairs",
  "You were the most unspoiled creature in the whole world",
  "It is so much more real than life",
  "Come and see me some afternoon in Curzon Street",
  "When the verities become acrobats, we can judge them",
  "Isaacs has been very good to us, and we owe him money",
  "Indeed, in some measure it was a disappointment to her",
  "It is the only way I get to know of them",
  "Years ago he was christened Prince Charming",
  "The man who had been shot in the thicket was James Vane",
  "He was not to go to the gold-fields at all",
  "Anything would be better than this dreadful state of doubt",
  "It has a perfect host, and a perfect library",
  "It is the feet of clay that make the gold of the image precious"
];

export default sentences.map((sentence) => {
  return sentence.replace(/\s/g, '␣').toLowerCase();
});
