const sentences = [
  'xido hxcdlpz.lcetmwcohcdkz.rsqjt',
  ' jcakdtv,vvivycozct,adfazldideh ',
  'kgmcdqmjii,loqc,qwh exqfplanhuse',
  'd,xho,qhsxlss cqte socyfe,hqdb.y',
  'wt,ttjaeqaynybzwbjugrpqfymaostn ',
  'tfesqsujjzebvmfhcgvznhpweksmairg',
  'owrwcxanvejockbj.zheixzjweelrxh,',
  'tyactngic.mvefnqctvfrfqnepucjist',
  'm.gsdsxzdwacdchkl  enavnkvntzsbx',
  'gmjy,mfiw,mnymhhbmwn.ob bickjinu',
  ' nshrlojxbuq,jfwvlzbxmqetfkysz,d',
  'pauxosddyo,ma.osgljtxtpeh  jnway',
  'yjb jytgjfkpdatddrke.alzjk,fmihj',
  'dvkjldjxy in.t,vxr ,yjsn.xlxkr y',
  'bhczgmjcvpifqucblinfasm dg fxvcy',
  'whaxih sex  tzbohbxkivjgqjuqjuki',
  ',xa.mrnuqlngkjwtyypwcryuvt,zcexj',
  'assdofkrag zv.vwjghrwfubdkenpuha',
  'v fwsiqwdkwtsarbn.qroaqq.qsxcvwh',
  'kv,dggkqsevnbja,hdjjbv,pr, coekb',
  'xgknscvw yjbscrhgntdhieiyrue wnb',
  'mflalloihnbtml cxebyldnjiz jlo m',
  'm.,ekftyvvzkoklpikcia,d ixfkhoi.',
  'bfgcoqmadnkdr,oopkietabatvkx,fwp',
  '.ssfa ag.aoov.,mbtmkocajutmsbnnl',
  'pnwlutakijtbeakxsajblrpfxul ywlh',
  'u jk,nrpobpb,gynonlzsddvfnpbffmd',
  'g.isbbxoxol et,ljjxse.ycv o,rpvm',
  'czk, fwykozanpnzra,zvp.haugi,qw.',
  'nus.bzam.x ftxhkutzwk qisrbfhzyz',
  'adolrzzbguzliemxzxomugs,puzs,kpk',
  'nfgw wlollzjdfdjitykea e lrqcvro',
  'ujgmkuxqptbrkpncdiigmrokzsfwnzmd',
  'qci.gmfdlmhgytaiyhyvohovhbmyghn,',
  'tjjnij.cyjyrfvnrgvrcfogxbvuifsye',
  'sjnyeqs, dbqwqck,xzvpsjkyqy,reix',
  'wveh.nou ,zqsldlopjouqmvsuol cye',
  'esnulyuif.jf.dcaxgzo,jsfmmrhpgqm',
  'gll,ejqgwwbqjkvakremtvp,iiqeub c',
  'lsoxofeb,nncp hemh.eeialivekeon ',
  'bdhdcirhok.,pjhvtlizj,otkhpmyppw',
  'ba .ovjzjtkxmnafiudzhyn.zjcotvqb',
  'ihw olgefs.jowy,frp,vdjaogwxi,.y',
  'mmvoxpmrhynwfbrxyttvxglnz.ozr,qa',
  'zshcytggvprl utbbdppojt fjvlxxsn',
  'lecdbtgzehuxl.qsbzjfckzivlqkba c',
  'ncna,cznujguxnuje,zzaivqbamhwhwy',
  'yvc,tbta .jvkeospesi plxsygphplu',
  'dnllqpharlrta.jbod,k rdbwbnmtqrp',
  'fqjrvyl s .rrgyakpfivcvnic.mni..',
  'uonawdjmrxirxcqofkoa.anqg.caewqd',
  'zcbmiucdggok.fyhptuhlmpnoouucnji',
  ',.paxgvlqlnqilwga.ihmci.eh,uhg c',
  'euqh.bml,s ig,m tmh,lrjjphcykuch',
  'lnnzpslhkr.dxryfimvujajid bcvuqw',
  'lnvk nrfetrxnvjzucoy.wmmuoegwygj',
  'qgaxhzihevfgpducg,p,hwuhivfmerxm',
  'nikjkbsncszpdojoxb,pnfifegjvf rt',
  'rhzvaid,pzjcamvfu poffdhtz.pya l',
  'oivqcrrgozbcpy  h wauhikfvaxxqle',
  'ydunts ibkkdbtwecm,hswsufuxfsl.p',
  ',.ywmvpjqyrxvjug.,sidznmusj irqw',
  'ym.qmkiegfghnzisthgpynvob.gjdtoc',
  'hwwd cos,zxsgk dkfrmzsjxyc.uiulz',
  'yb,tutvitanj.wagfxptfbom hkkdirr',
  'xeakcgqoohvplnvwtqal,buslnpvbnpi',
  'oxnzumhyecpkkchzoscyo,rdop.qwljl',
  'tfpbxoyphumm nssdfdnl whgfsxhrnv',
  'yjaqjhakiiw.spdqijypkhprtrcryfnp',
  'q,kxhplntnp l  snm.lnxa iuqrajep',
  'fftkubzp xiqibldwcduiaihmccudko ',
  'ehihwguiolaqneyfr.dqvz.nohcmjefb',
  'wauzhfgwjwppjprdwhdtamdejwrhbub ',
  'ixrbgtfjlfd.itafcbeaod.asdk.magg',
  'ixutcgnd.pcravvscgqi.opjhyiyde,a',
  'wsltuwgzxpzobrvxionn,oyxbezklxgg',
  'dtzixjafzqguqddut yq.dyxfabmoujw',
  'b zz mk.qesayswe.krlwlvxvaxcfezw',
  'ect.pmtwkvuur mcwpeqeduhwxf,aihp',
  'awr,z lw.clywtyucioigqxoawtxmbzd',
  'tfe joki ellrvaliwdczoubk.zhze ,',
  'wnqoxanyt,xwwwyrwtipifdmiettsipz',
  'zgeyjmakubivughyw.i.qd.gtd.ih,ep',
  'mtb dbptajayvitvsvwg.vtnrgkihvzb',
  'udgvwwtomzaczlwrsfdvealffbj.dedb',
  'azdmfupnck.nrnuayxpbtx,lf dcszqg',
  'kqdbssvdorbaeuemknxj,dsk..dcshdn',
  'gta.uk.pjoalhnstsojwbepwxybawxzu',
  'bgny skqusqgevt,dyfx,tcfwlhchwhs',
  'zle vtmxkh,jep.abj,tvzwn j fqlwi',
  'p u gymfw.lqzashsrckrztoixstjfld',
  'poij kpsqsoyd  cgaainfnkcgdlsxw ',
  'jvv js,hhjrsfl.rcoc ,qympbdk.aor',
  'ekjqyvguohejlftci.qp iddxvpqapgi',
  '.raxava iglqctg.dfjmxot.g ryaezw',
  'ga,dgblluo yhvruw,hsfkywl ljevut',
  'kxsuqvsllhgzjsvgkqpvbradvsin.yfz',
  'wz,sboctlqgdjcvievbr.hghhgsvzunp',
  'vfpr uujwztdbpbegjftbyrtp mv.guh',
  'rtqpgx,ogljbylpuyhqh,arneahmpktx',
  'xxhemn cqzlzxoi. oo.tuxxs rh.edc',
  'szmjxz se.voknsii iiuo.lfxnaa.fp',
  'ez xbvq,duq.onjrjadntibq,thu eow',
  'qr.bgnyhgjrcoopnxizpjehq,ru,wqp ',
  'yhvjavsbkbxyym p ioj fdkdvgoxvgj',
  ',fabdgamyxxmekc,zdlfzcobdtmha,bh',
  'jcjslq,qqzjozlflfaozkbmobpxerhdn',
  '.bfferkdbcypl rbcavsjt wurhvs,in',
  'vpltxh.pzcqqnrnlzvjqzwxmkwp.cpae',
  'npbplvx,cgz,mlrntolonoo,xxmeu.wg',
  'lyj.r,dfhtl.q.pei. v.,zfkxbb.aii',
  'drvvmqfmt,qpb.cyt,pkrwsvy tyo.io',
  'ujskaveoiupqqbkwhgtkypzdxhehvtgv',
  'zbrvkrpwzejoh c,qimagvmdgqnetira',
  'qdafdyuwqdpknhczarq mungvbrsxtyw',
  ',qmbqqhqz rshm,dea,.kp,bctxwqgbi',
  'xhj,lhhggk.zj,byg cqzzenqzvrlidw',
  'kgjx.arihy.f,rycyn,hkjfz,clmaehv',
  ',zixb,dmpe,gv ,h,,uzjfyadtaopixu',
  'vafgv,kye,ehlulrhwkho.ykmtsincjz',
  'ozligbueedejd.ktnncjyh oopzx,qpv',
  'kdfdznakgayhrsnsqisl ejqpjr,warq',
  'yy,ujfabi,eewvjngdfzrbvv.mfzxfx.',
  'b ti.dkrikpksqpgmrsygra xjsqmszj',
  'dasweoyemsfdo. .p naqme.lkfd.hui',
  ',isinihjzyp,,zbgyer,xmaejkbamvkd',
  'ezga xquhpphpwmjpbb xsnzrzkbsn i',
  'hqcepcw uastdmjsyahaldvj jo rwsx',
  'crdbspvhtyvklfoforewn.mfdnp .hdi',
  'm.kzghkvm pkgqyq,eggex,fpqtz fwl',
  'lxtldcxjwjqoponmdebpdwcrjbmgmkbp',
  'bbhcu,jvcgtckboyadae djswuhn,hmp',
  'cayqwgeql.qvztbhaw,xyualsd ,qutt',
  'ncphgi.p.srrxwxtlgkobphu,pbbt,hb',
  ',ohvqny..tskqcueksbinks.ovngyq.n',
  'wljphzlqbmjmzgx bt.xeljxc,kx.eca',
  'irjtnonqhnyjuc dnmdy tivfcvkogfg',
  'cgixnozlpmoa,evwb,ifxjlovhfbyrih',
  'lkbu bxkl, ahcbwpsulekw, untsa.a',
  'dkoumbuls.xlyjgufudvro.ftsiq ytn',
  'evfyzlnk.dmqfahamnabjxreowpghwvg',
  'cmsfjlex yhrp,a,zoxexrgnhxdojmtb',
  'scdsipgbepwlefl .fa cymrop.wom,z',
  'ixn ydcbb,dzjkhrhjpr,dnultxvv zv',
  'urolchjvxie,hu.zrpmajkqfcrzjtvaz',
  'uythhh.elpyfweq.r,m ivkcnilaqetd',
  'o. ieyisjvuapxeasjbyycpnqnhovyyg',
  'qlfwh ltknowcqkdw iry.euktvczpze',
  'a.garvrvl.pfjditeb lmzaoyo,ltngr',
  'izimbs,,sc,kkrofmtzurpbhnvp.sada',
  'avwvheovw,ctmznrimkrtu kxvfza,aa',
  'tybp,btdpllzovwirtmrtwk,dzyi,gef',
  'ewwsf,ck o.fmaschkhkafapwnipeqny',
  'ggefea.xtrehguwprlrvtbrqwpz tpvu',
  'midhy chzzmcbo,pydkbsccjhzligrey',
  'pusmfdhasih,iufgext,hptzkpiujuhg',
  'rzqhslryjr,iuqalefxnpinehzpx,,sv',
  ',tgzldquzbkhpmxpm.nf.gxamwm,rvex',
  'hbtypmjrppwizbtmppixpaz tpciffcz',
  'r.cpijlcfdwpb..nqgjzufcxblf.qha ',
  'ocaolg ptbuthnlkor,ujebrqqumcul.',
  'jpllizdb. wzescojnsikacberaknxek',
  '.nlmaapuicpxee gohfpjp,bdqsmtc,d',
  'yhjtz.qkf ferp pbotuxorjpnhumaii',
  'mhswarcw.fnjaongisidc gnabffiw,b',
  'bwiaq,wjfhsm,rjubnwwmsqrrq,txrmt',
  'kqxovlhzl h cfpxjswdej,kg.gdxgvp',
  ',xop zqbtvtpzagcpmurwxdxb.hstxft',
  'hprytskyltjvznorfdeqerkut,ihlir ',
  'oyprkhasxwvxbclgtvkeiw,oqkkbqwwr',
  'yyhziylaeqjbtmbrsrdyhgykeo.uawev',
  'znzhez.ursfgyaqy.anf..azlltglbnq',
  'mfmpxuedeqjau vhk,wgtex.,l.ultt.',
  'hcvlfzzcpnixwwbbhjunavjkcrtjhku,',
  'xhi xruffpetkephevyqwmwxwxyyybjb',
  'akjkejscbfjrepwuosg ptt,l.wlbgpm',
  'zvl,cpkqgxwjo,ytye,.tiqrqflmqegw',
  'c,d idvidtlazpjqx roarhstucmmzwi',
  'o,hryledxfehpgzx vyua trnzfwsiuf',
  'wmqlmsbowodjecbnzsucsjaptnmpaihx',
  'soasgumkiqrotvn,uzgx p.lht,sdbab',
  'jjwdqqarxoyvbdsipyvwgrzzxkfo av ',
  '.xzhgbrpgvgxsnqg.hemfwpcc,gbzwhl',
  'panfy,qlghbhxn ijofoe,hopmttoxfs',
  'xptatyyqkckyxdwfxkvzangkdbjvvsze',
  ',nbigydamxjwzx gscbthyku,o lwlgv',
  'wxxulvivmeamd offna,llbkp bfupgm',
  'fwaphyxyy,tzdzsimhpsmqgi.lavdaao',
  'l,sprqvni.bs.ljjvfaawepuijplmbhd',
  ' fwdlvgwvuheenymfuhrks n.hdbrkoq',
  'bxbejtqvtpmwcqr,kc kmgzesmakxgls',
  'mppzjhyxwnojzhwpauflzjujweoy,gdu',
  'pihepbrtvrcapjlgr.axeqp ipw.mpmd',
  'pecweodggykeb,puimsboptctawxqtou',
  'oayzabetef.nphlzluoha..qc,qqbpxm',
  'vfeffz ki,fgndfehox.heuvfn.xkyyk',
  'cpooeqf c xjv uq w hpjzwe  f pxs',
  'v qzqhzicpt,a.priesectubwkc.lcrq',
  'dy csxjru.dmttu,pydgxqrjitaeztkm',
  'tqqoaufwmpz ybn kcpxasgivsass eq'
];

export default sentences.map((sentence) => {
  return sentence.replace(/\s/g, '␣');
});
